language: node_js
notifications:
  email: false
node_js:
  - 0.10
before_install:
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install -g karma
  - cd src
  - bower install
  - cd ..
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"